[package]
name = "tearchan-ecs"
version = "0.0.1"
edition = "2018"

[dependencies]
derive-new = "0.5"
serde = "1.0.125"
# Internal modules
tearchan-util = { path = "../tearchan-util" }

[dev-dependencies]
serde_json = "1.0.64"
