[package]
name = "tearchan"
version = "0.0.1"
edition = "2018"

[features]
default = []
metal = ["tearchan_graphics/metal"]
wgl = ["tearchan_graphics/wgl"]
dx11 = ["tearchan_graphics/dx11"]
dx12 = ["tearchan_graphics/dx12"]
vulkan = ["tearchan_graphics/vulkan"]

[dependencies]
serde = "1.0.116"
derive_builder = "0.9.0"
nalgebra-glm = { version = "0.8.0", features = ["serde-serialize"] }
winit = { version = "0.22.2", features = ["web-sys"] }
gfx-hal = { version = "0.6.0", path = "../gfx/src/hal" }
intertrait = "0.2.0"
linkme = "0.2"
tearchan_core = { path = "tearchan_core" }
tearchan_graphics = { path = "tearchan_graphics" }
tearchan_horde = { path = "tearchan_horde" }
tearchan_utility = { path = "tearchan_utility" }

[workspace]
members = [
    "tearchan_core",
    "tearchan_graphics",
    "tearchan_horde",
    "tearchan_utility",
    "examples",
]
