[package]
name = "tearchan"
version = "0.0.1"
authors = ["inoutch <akiandaki@gmail.com>"]
edition = "2018"

[features]
default = []
metal = ["gfx-backend-metal"]
gl = ["gfx-backend-gl", "gfx-backend-gl/glutin"]
dx11 = ["gfx-backend-dx11"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
env_logger = "0.7.1"
derive_builder = "0.9.0"
image = "0.23.4"
winit = { version = "0.22.2", features = ["web-sys"] }
gfx = "0.18.2"
gfx-hal = "0.5.3"
gfx-backend-empty = "0.5"
nalgebra-glm = { version = "0.7.0", features = ["serde-serialize"] }
serde = { version = "1.0.111", features = ["derive", "rc"] }
serde_json = "1.0.53"
tobj = "2.0.1"
texture_packer = "0.21.1"

[dependencies.gfx-backend-gl]
version = "0.5.1"
optional = true

[dependencies.gfx-backend-vulkan]
version = "0.5.1"
features = ["x11"]
optional = true

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies.gfx-backend-metal]
version = "0.5.1"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx11]
version = "0.5.1"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.5.1"
optional = true

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies]
objc = "0.2.7"
objc-foundation = "0.1.1"

[dev-dependencies]
float-cmp = "0.7.0"

[build-dependencies]
shaderc = "0.6.2"
