[package]
name = "tearchan_horde"
version = "0.0.1"
edition = "2018"

[dependencies]
serde = "1.0.18"
downcast-rs = "1.2.0"
tearchan_core = { path = "../tearchan_core" }
tearchan_utility = { path = "../tearchan_utility" }

[dev-dependencies]
serde_json = "1.0"
